nameOverride: ""
fullnameOverride: ""

securityConfigs:
  accessTokenKey: ""
  accessTokenDuration: 15m

##
## Authentication API
##
auth:

  replicaCount: 1

  image:
    repository: martikan/carrental_auth-api
    pullPolicy: IfNotPresent
    tag: "v0.0.1"

  postgres:
    driver: "postgres"
    host: ""
    password: ""
    user: "auth"
    db: "auth"
    port: "5432"
    ssl_mode: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: "auth-api-sa"

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: carrental-auth.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - carrental.local

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

##
## Cars API
##
cars:

  replicaCount: 1

  image:
    repository: martikan/carrental_cars-api
    pullPolicy: IfNotPresent
    tag: "v0.0.1"

  postgres:
    driver: "postgres"
    host: ""
    password: ""
    user: "cars"
    db: "cars"
    port: "5432"
    ssl_mode: ""

  imagePullSecrets: []

  serviceAccount:
    create: true
    annotations: {}
    name: "cars-api-sa"

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: carrental-cars.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - carrental.local

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
