apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secrets
type: Opaque
data:
  pgUser: {{ .Values.auth.postgres.user | b64enc }}
  pgPassword: {{ .Values.auth.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cars-db-secrets
type: Opaque
data:
  pgUser: {{ .Values.cars.postgres.user | b64enc }}
  pgPassword: {{ .Values.cars.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  auth_api_admin_user: {{ .Values.auth.username | b64enc }}
  auth_api_admin_user_password: {{ (include "auth.authAdminUserPassword" .) | b64enc }}
  accessTokenKey: {{ .Values.securityConfigs.accessTokenKey | b64enc }}
