{{- if .Values.auth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "car-rental.authServiceAccountName" . }}
  labels:
    {{- include "car-rental.labels" . | nindent 4 }}
    component: auth-api
  {{- with .Values.auth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.cars.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "car-rental.carsServiceAccountName" . }}
  labels:
    {{- include "car-rental.labels" . | nindent 4 }}
    component: cars-api
  {{- with .Values.cars.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}